# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "E0/oAje0pT3ih/mP6fJd1FEqx/d17ZSvTOUw5MzUCrYJ7W3gaxqWouezY9QeqVwg7m/mPIT+ijrhQUR/nd21yI/G/JhuOFehw17KjyT+r/qpUjfr83aHq+L38iBWzIemOluaIpIWLuSHG2CXlyd2DcSu8Uq/I/ri1Vggubn91J0sjmt5frYYMvTZPllcV3S2yXTQZG2wtDf9/fnpg9sVJB+7Z4Bt0u+qJUVKGSzhpAwFXTMQfTlRa9vXPJJqi3Mdrc06lNlTuBrjWU3U/XhdwxQMMkg2G2X9YEkIrh4Q544ctpLJP+w/RK/QDpw3F7reK4p78W4hZozryyoeUDTEFag4yKfik3Zh8fUQw23+YVmam/acFwtjy5/fv0uXf+Sb0nBsaCOI99jyVmcso1mHkddwvpsTCY/gh5nGk1m8sXviSUMWpiE1WNiU77W73Zjrlwu2cOsAzdq7Xoe3mfrI/lfMNCBL9XnzXwKhzYiw3WTWorDlQft6ox5hZGxQUNWFsBAg91MbsA2EnGPe9UstL9u9pfJET0rkPRrOtJwZMckua8L5LZjoozjdXLTr2xYe18Jvad8dtlVrYJ8L7N0m8SiIDCpv1bawtl/kkJiBrelgPZnM/PyFglqjPVW3ISRvOgpyc+SmrpGR3KHUSS+u78hGXRoDNHDuMPMu8hoDEHA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
