appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: E0/oAje0pT3ih/mP6fJd1FEqx/d17ZSvTOUw5MzUCrYJ7W3gaxqWouezY9QeqVwg7m/mPIT+ijrhQUR/nd21yI/G/JhuOFehw17KjyT+r/qpUjfr83aHq+L38iBWzIemOluaIpIWLuSHG2CXlyd2DcSu8Uq/I/ri1Vggubn91J0sjmt5frYYMvTZPllcV3S2yXTQZG2wtDf9/fnpg9sVJB+7Z4Bt0u+qJUVKGSzhpAwFXTMQfTlRa9vXPJJqi3Mdrc06lNlTuBrjWU3U/XhdwxQMMkg2G2X9YEkIrh4Q544ctpLJP+w/RK/QDpw3F7reK4p78W4hZozryyoeUDTEFag4yKfik3Zh8fUQw23+YVmam/acFwtjy5/fv0uXf+Sb0nBsaCOI99jyVmcso1mHkddwvpsTCY/gh5nGk1m8sXviSUMWpiE1WNiU77W73Zjrlwu2cOsAzdq7Xoe3mfrI/lfMNCBL9XnzXwKhzYiw3WTWorDlQft6ox5hZGxQUNWFsBAg91MbsA2EnGPe9UstL9u9pfJET0rkPRrOtJwZMckua8L5LZjoozjdXLTr2xYe18Jvad8dtlVrYJ8L7N0m8SiIDCpv1bawtl/kkJiBrelgPZnM/PyFglqjPVW3ISRvOgpyc+SmrpGR3KHUSS+u78hGXRoDNHDuMPMu8hoDEHA=
