travis:
  secure:
    BINSTAR_TOKEN: WcE3ECfI/F56aTQHeNMfppPdHfi9oqiQxBdRDRGbEnfl1p5g1VCs9ONMNIrueK1BX3MNU57GlX8A5RU2mEKASBMXguQRk7p+CGgE5P7WvPyZAszlJeQBN4yNfm4iS+nScF6KMRZvl2360ebdBDbd9DhHo9gGqm/GBnRpb14Xwe2q0PDUp9667ZLJKYDvBx4EeGdVXdwVlxln3aKy7cHQJjziZYKLurMK8Oh6lUOMCceAFi1wUor40lk5GNO8If74wXGneEejxLURoay5Jr3WJoL+j4vxYb6eX5dBZp39rjScA6qjkiEDIkshGwKeU7Xv7oVYf7y3dNfDfs0Or7gevH+32HPbmnmkWz743BKlU2K39T0DmYrbz2SAyXxIqTXPt/qmxcwhaplNEElia2czOx16qAet6PM7OwEa48lH0ToGhG1+oneXWLemycMur2FXBRYeY2alKvSxfPqfyvQeCHU43tQmEx1zYRKJVcfqOm4PAwGCs++SyBsZKqIhdSkqGD7iPtzAldhMMcfbrUQ0/H9DnC9m+oDLZ9/DuBY3CTGHFIsEma3PnZ5myxMSQskkZaZ6vnqEPFOJcMj0IBtgfRzo8g0tyrf8ICVGK0aMaiJBtLX2mcD2pFIomvy679Ocf6wks8rd7RMRxCUWF+IgxJqZlCu+2g/HvuSBqp4kY/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
